baseURL = "http://mysqltopgsql.com/"
languageCode = "en-us"
title = "MySQL to PostgreSQL"

theme = "ananke"
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 12
googleAnalytics = "UA-47059482-4"
enableRobotsTXT = false

[params]
  description = "Migrate from MySQL to PostgreSQL"
  github = "https://github.com/dimitri/pgloader"
  custom_css = ["css/custom.css"]

[author]
  twitter = "tapoueh"